Updated Typescript to 4.7
AndcultureCode/AndcultureCode.DotnetReact.Boilerplate pull request #84
Opened 2022-06-24 15:35 UTC by coykwan

- [ ] Related GitHub issue(s) linked in PR description
- [ ] Destination branch merged, built and tested with your changes
- [ ] Code formatted and follows best practices and patterns
- [ ] Code builds cleanly (no _additional_ warnings or errors)
- [ ] Manually tested
- [ ] Automated tests are passing
- [ ] No _decreases_ in automated test coverage
- [ ] Documentation updated (readme, docs, comments, etc.)
- [ ] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

2022-07-07 12:05 UTC, jdahlinrsm approved these changes

2022-07-07 18:48 UTC, rllowman requested changes
Left a few comments. I'm also open to pairing with you to figure out the test coverage stuff. I'd like to make sure the `itemIdToDraggableId` function is well tested, but some of the other areas that are missing coverage are less important.

2022-07-07 18:48 UTC, rllowman commented on frontend/src/molecules/lists/drag-and-drop-list-box.tsx
> +            if (itemIdAsObject?.toString() != null) {
Remove the parenthesis so as not to invoke `toString`. We want to check that the function itself exists, not that its return exists.

My bad on this one, I made the change and never updated the snippet.

2022-07-07 18:48 UTC, rllowman commented on frontend/src/molecules/lists/drag-and-drop-list-box.tsx
> +                        draggableId={JSON.stringify(item.id)}
Make sure to call `itemIdToDraggableId` here instead of `JSON.stringify`.

2022-07-07 18:48 UTC, rllowman commented on frontend/src/molecules/lists/list-box.tsx
> +export interface ListBoxItem<T extends any> {
You should be able to remove the `extends any`.

2022-07-14 17:24 UTC, myty approved these changes
Looks good!

2022-07-14 20:02 UTC, merged